### ISSUE TITLE
libprimme.so needs to be linked to blas and lapack

### ISSUE THREAD

**Issue by yurivict** [primme/primme#23]
```
$ ldd -a ./work/primme-d089bec/lib/libprimme.so
./work/primme-d089bec/lib/libprimme.so:
	libc.so.7 => /lib/libc.so.7 (0x800823000)

$ nm -a ./work/primme-d089bec/lib/libprimme.so
...
                 U zaxpy_
                 U zcopy_
                 U zgemm_
...
```

There are unresolved lapack/blas symbols.

**Comment by yurivict** [comment]
I think, you also need to remove this ```-Wl,dynamic_lookup```.

**Comment by jxy** [comment]
Not if you want to link to different libraries when you create your executable.  It is better without, so you can try your compiled libprimme.so with the reference implementation, with ATLAS, with openblas, or others.

**Comment by eromero-vlc** [comment]
With the changes introduced by @jxy you can make libprimme.so to be linked with whatever you put in LDFLAGS. For instance

make solib LDFLAGS='-llapack -lblas'
ldd lib/libprimme.so
        linux-vdso.so.1 (0x00007ffecc37e000)
        liblapack.so.3 => /usr/lib/x86_64-linux-gnu/liblapack.so.3 (0x00007ff542554000)
        libblas.so.3 => /usr/lib/x86_64-linux-gnu/libblas.so.3 (0x00007ff5422f9000)
        ...

**Comment by yurivict** [comment]
It's safer to add ```-Wl,--no-undefined```, so that missing symbols will be noticed during build.
It also needs -lm because it references various math symbols.

**Comment by jxy** [comment]
My point is that you don't need to resolve all the symbols for a dynamic library.  You only need it at the executable binary link time.

Unless you want to depend on some specific provider of a libm and liblapack / libblas, by default, you don't need to provide those.

I wouldn't want to rebuild and reinstall libprimme just to link my executable to a different lapack/blas implementation, because I might want some binary to use libopenblas+libopenlibm, and some other to use MKL, or libcublas.
