### ISSUE TITLE
About 'maxiter' in Python Interface

### ISSUE THREAD

**Issue by lightpeak008** [primme/primme#56]
In Python Interface's `eigsh()`, I wanted to use `maxiter` parameter to instruct PRIMME to stop after reaching the specified number of Outer Iterations. I expected to get the eigenpairs it has computed till then and the stats to know which of them are marked as converged via `stats['hist']['nconv']`. But, adding the parameter raises a `PrimmeError` exception and does not return anything. Is it possible to get the eigenpairs (converged or not) the routine has computed till then?

**Comment by eromero-vlc** [comment]
Hi S Shri! I have uploaded a new version of primme (3.2.1) that adds options to return converged and unconverged values instead of raising an exception. In `eigsh`, set the option `raise_for_unconverged` to `False` to return the converged pairs. And, if you set the option `return_unconverged` to `True`, the function returns up to `k` eigenpairs, and you can check how many are converged with the ` stats['hist']['nconv']`. See these examples:
```python
import numpy as np, scipy.sparse, primme

A = scipy.sparse.spdiags(np.asarray(range(100), dtype=np.float32), [0], 100, 100)
evals, evecs = primme.eigsh(A, 3, tol=1e-3, which='LA', maxiter=30, raise_for_unconverged=False)
print(evals) # [ 98.99946 ]

evals, evecs = primme.eigsh(A, 3, tol=1e-3, which='LA', maxiter=30, return_unconverged=True)
print(evals) # [ 98.99947 97.88711 96.16563 ]
```

**Comment by lightpeak008** [comment]
Thank you for your quick response @eromero-vlc. I have tested the newly added feature. I noticed that input parameter `maxiter` sets `maxMatvecs` parameter in 'primme.pyx' (see Line 551) instead of `maxOuterIterations`. I got around that by passing `maxOuterIterations` as an argument to `eigsh()` and it works as expected. For small test cases where `maxOuterIterations` is set to be larger than the expected number, there is no change in the runtime behavior. For a smaller number, `stats['numOuterIterations']` is always less than or equal to the number. So, apart from the `maxiter` parameter, the implementation works as intended.
